localhost:
    local: true
    stage: test
    roles: test
    http_user: www-data
    deploy_path: /home/dmitry/Projects/frontend-server-deploy
    dbhost: 127.0.0.1
    dbname: mir24_7
    dbuser: root
    dbpass: example
    dumpfile: mir24_7.sql
